# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 90409455136ca17216ed27366de3117fbe1a96794383588d8a1956b3d7d3a188238d1c52476f644c4137ef0afacedeb71b6c505c36c13e671dce06f190555480

test:
  secret_key_base: 4401b3025daa499e4c97244b173d04af15acc931b993d58424b6b24b40276653c5eb3cb06ae598875a96f2ffe60da370367241a8d009e603c1c4ce7af674dcfa

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
